# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca1f46167b3cf49fd5e7afd08e5220966bf521c14e485a6748045f9d6826259000aad8b011171b7b86b29c57c443cc29881cf1a37086ec3daa741b85ae4a00e

test:
  secret_key_base: 13f5df642083e4ad7f210cfc1e6824670d744bd4ed043f742ab020bdd877fcee77d31e5f49a3a1dee8ce33fc5ee844d1ab0f3b82345b8b115faf4522dc677935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
