require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MangasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Manga. As you add validations to Manga, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MangasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all mangas as @mangas" do
      manga = Manga.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mangas)).to eq([manga])
    end
  end

  describe "GET #show" do
    it "assigns the requested manga as @manga" do
      manga = Manga.create! valid_attributes
      get :show, {:id => manga.to_param}, valid_session
      expect(assigns(:manga)).to eq(manga)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manga as @manga" do
      manga = Manga.create! valid_attributes
      get :edit, {:id => manga.to_param}, valid_session
      expect(assigns(:manga)).to eq(manga)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Manga" do
        expect {
          post :create, {:manga => valid_attributes}, valid_session
        }.to change(Manga, :count).by(1)
      end

      it "assigns a newly created manga as @manga" do
        post :create, {:manga => valid_attributes}, valid_session
        expect(assigns(:manga)).to be_a(Manga)
        expect(assigns(:manga)).to be_persisted
      end

      it "redirects to the created manga" do
        post :create, {:manga => valid_attributes}, valid_session
        expect(response).to redirect_to(Manga.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manga as @manga" do
        post :create, {:manga => invalid_attributes}, valid_session
        expect(assigns(:manga)).to be_a_new(Manga)
      end

      it "re-renders the 'new' template" do
        post :create, {:manga => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manga" do
        manga = Manga.create! valid_attributes
        put :update, {:id => manga.to_param, :manga => new_attributes}, valid_session
        manga.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manga as @manga" do
        manga = Manga.create! valid_attributes
        put :update, {:id => manga.to_param, :manga => valid_attributes}, valid_session
        expect(assigns(:manga)).to eq(manga)
      end

      it "redirects to the manga" do
        manga = Manga.create! valid_attributes
        put :update, {:id => manga.to_param, :manga => valid_attributes}, valid_session
        expect(response).to redirect_to(manga)
      end
    end

    context "with invalid params" do
      it "assigns the manga as @manga" do
        manga = Manga.create! valid_attributes
        put :update, {:id => manga.to_param, :manga => invalid_attributes}, valid_session
        expect(assigns(:manga)).to eq(manga)
      end

      it "re-renders the 'edit' template" do
        manga = Manga.create! valid_attributes
        put :update, {:id => manga.to_param, :manga => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manga" do
      manga = Manga.create! valid_attributes
      expect {
        delete :destroy, {:id => manga.to_param}, valid_session
      }.to change(Manga, :count).by(-1)
    end

    it "redirects to the mangas list" do
      manga = Manga.create! valid_attributes
      delete :destroy, {:id => manga.to_param}, valid_session
      expect(response).to redirect_to(mangas_url)
    end
  end

end
